global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'pos-backend'
    metrics_path: '/api/metrics/prom'
    scheme: 'http'
    static_configs:
      - targets: ['host.docker.internal:5757']

